# Generated by Django 5.1.4 on 2025-11-04 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para UI', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, help_text='RUT del cliente sin puntos ni guión', max_length=12, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('contacto', models.CharField(blank=True, help_text='Nombre de contacto', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('emails_procesados', models.IntegerField(default=0)),
                ('adjuntos_descargados', models.IntegerField(default=0)),
                ('ofertas_extraidas', models.IntegerField(default=0)),
                ('ofertas_insertadas', models.IntegerField(default=0)),
                ('ofertas_actualizadas', models.IntegerField(default=0)),
                ('errores', models.TextField(blank=True)),
                ('duracion_segundos', models.FloatField(default=0)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ETL Logs',
                'db_table': 'etl_logs',
                'ordering': ['-fecha_ejecucion'],
                'indexes': [models.Index(fields=['-fecha_ejecucion'], name='idx_etl_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad física en inventario')),
                ('stock_minimo', models.IntegerField(default=10, help_text='Stock mínimo antes de alerta')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta al público', max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo/compra', max_digits=10)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras EAN', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='core.categoria')),
                ('proveedor_principal', models.ForeignKey(blank=True, help_text='Proveedor principal de este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Producto en Inventario',
                'verbose_name_plural': 'Productos en Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_catalogo', to='core.categoria')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que ofrece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos_catalogo', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Catálogo',
                'verbose_name_plural': 'Productos de Catálogo',
                'db_table': 'productos_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bajo_stock', 'Bajo Stock'), ('estacional', 'Estacional'), ('epidemiologico', 'Epidemiológico'), ('ml', 'Machine Learning')], max_length=20)),
                ('cantidad_sugerida', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('razon', models.TextField()),
                ('confianza_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fuente_datos', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Sugerencias de Compra',
                'ordering': ['-prioridad', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número de documento de venta', max_length=50, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=50)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('hash_unico', models.CharField(blank=True, db_index=True, help_text='Hash MD5 único para detectar duplicados: MD5(numero+cliente_rut+fecha)', max_length=64, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='VentaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Venta Histórica',
                'verbose_name_plural': 'Ventas Históricas',
                'db_table': 'ventas_historicas',
            },
        ),
        migrations.CreateModel(
            name='ArchivoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('ofertas_extraidas', models.IntegerField(default=0)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(blank=True, max_length=100)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('etl_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_procesados', to='core.etllog')),
            ],
            options={
                'verbose_name_plural': 'Archivos Procesados',
                'db_table': 'archivos_procesados',
                'ordering': ['-fecha_procesamiento'],
                'indexes': [models.Index(fields=['hash_archivo'], name='idx_hash_archivo'), models.Index(fields=['-fecha_procesamiento'], name='idx_fecha_proc')],
                'unique_together': {('etl_log', 'hash_archivo')},
            },
        ),
        migrations.CreateModel(
            name='OfertaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(blank=True, help_text='Laboratorio fabricante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.laboratorio')),
                ('producto_catalogo', models.ForeignKey(blank=True, help_text='Producto del catálogo de proveedores', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.productocatalogo')),
            ],
            options={
                'verbose_name_plural': 'Ofertas de Laboratorios',
                'db_table': 'ofertas_laboratorio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activa', 'fecha_fin'], name='idx_oferta_activa_fecha'), models.Index(fields=['laboratorio', 'activa'], name='idx_oferta_lab_activa'), models.Index(fields=['producto_catalogo', 'activa'], name='idx_oferta_prod_activa')],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(db_index=True, help_text='Código del producto según el proveedor', max_length=100)),
                ('nombre_en_catalogo', models.CharField(blank=True, help_text='Nombre del producto en el catálogo del proveedor', max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Si el mapeo está activo o fue descontinuado')),
                ('confianza', models.DecimalField(decimal_places=2, default=100.0, help_text='Nivel de confianza del mapeo (0-100%). 100% = manual, < 100% = automático', max_digits=5)),
                ('fecha_mapeo', models.DateTimeField(auto_now_add=True)),
                ('mapeado_por', models.CharField(default='manual', help_text="Origen del mapeo: 'manual', 'automatico', 'ml'", max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el mapeo')),
                ('producto_interno', models.ForeignKey(help_text='Producto del inventario interno', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.producto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que usa este código', on_delete=django.db.models.deletion.CASCADE, related_name='producto_mappings', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Mapeo Producto-Proveedor',
                'verbose_name_plural': 'Mapeos Producto-Proveedor',
                'db_table': 'producto_proveedor_mapping',
                'ordering': ['-fecha_mapeo'],
                'indexes': [models.Index(fields=['codigo_proveedor', 'proveedor'], name='idx_codigo_prov'), models.Index(fields=['producto_interno', 'activo'], name='idx_prod_int_act')],
                'unique_together': {('codigo_proveedor', 'proveedor')},
            },
        ),
        migrations.AddIndex(
            model_name='productocatalogo',
            index=models.Index(fields=['codigo'], name='idx_cat_codigo'),
        ),
        migrations.AddIndex(
            model_name='productocatalogo',
            index=models.Index(fields=['proveedor', 'activo'], name='idx_cat_prov_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='idx_prod_codigo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'stock_actual'], name='idx_prod_activo_stock'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['hash_unico'], name='core_venta_hash_un_57d01a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha', 'cliente'], name='core_venta_fecha_0741c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['fecha'], name='ventas_hist_fecha_a32ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['cliente_id'], name='ventas_hist_cliente_8fac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['producto', 'fecha'], name='ventas_hist_product_6a341a_idx'),
        ),
    ]
