# Generated by Django 5.1.4 on 2025-11-03 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('ofertas_extraidas', models.IntegerField(default=0)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(blank=True, max_length=100)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Archivos Procesados',
                'db_table': 'archivos_procesados',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(db_index=True, help_text='Código del producto según el proveedor', max_length=100)),
                ('nombre_en_catalogo', models.CharField(blank=True, help_text='Nombre del producto en el catálogo del proveedor', max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Si el mapeo está activo o fue descontinuado')),
                ('confianza', models.DecimalField(decimal_places=2, default=100.0, help_text='Nivel de confianza del mapeo (0-100%). 100% = manual, < 100% = automático', max_digits=5)),
                ('fecha_mapeo', models.DateTimeField(auto_now_add=True)),
                ('mapeado_por', models.CharField(default='manual', help_text="Origen del mapeo: 'manual', 'automatico', 'ml'", max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el mapeo')),
            ],
            options={
                'verbose_name': 'Mapeo Producto-Proveedor',
                'verbose_name_plural': 'Mapeos Producto-Proveedor',
                'db_table': 'producto_proveedor_mapping',
                'ordering': ['-fecha_mapeo'],
            },
        ),
        migrations.CreateModel(
            name='VentaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Venta Histórica',
                'verbose_name_plural': 'Ventas Históricas',
                'db_table': 'ventas_historicas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='en_inventario_actual',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el producto está en el último Excel de inventario cargado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_carga',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última vez que este producto fue incluido en una carga de Excel', null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='fecha_fin',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='laboratorio',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='etllog',
            index=models.Index(fields=['-fecha_ejecucion'], name='idx_etl_fecha'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['activa', 'fecha_fin'], name='idx_activa_fecha_fin'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['laboratorio', 'activa'], name='idx_lab_activa'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['producto', 'activa'], name='idx_prod_activa'),
        ),
        migrations.AddField(
            model_name='archivoprocesado',
            name='etl_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_procesados', to='core.etllog'),
        ),
        migrations.AddField(
            model_name='productoproveedormapping',
            name='producto_interno',
            field=models.ForeignKey(help_text='Producto del inventario interno', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.producto'),
        ),
        migrations.AddField(
            model_name='productoproveedormapping',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor que usa este código', on_delete=django.db.models.deletion.CASCADE, related_name='producto_mappings', to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='ventahistorica',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.producto'),
        ),
        migrations.AddIndex(
            model_name='archivoprocesado',
            index=models.Index(fields=['hash_archivo'], name='idx_hash_archivo'),
        ),
        migrations.AddIndex(
            model_name='archivoprocesado',
            index=models.Index(fields=['-fecha_procesamiento'], name='idx_fecha_proc'),
        ),
        migrations.AlterUniqueTogether(
            name='archivoprocesado',
            unique_together={('etl_log', 'hash_archivo')},
        ),
        migrations.AddIndex(
            model_name='productoproveedormapping',
            index=models.Index(fields=['codigo_proveedor', 'proveedor'], name='idx_codigo_prov'),
        ),
        migrations.AddIndex(
            model_name='productoproveedormapping',
            index=models.Index(fields=['producto_interno', 'activo'], name='idx_prod_int_act'),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedormapping',
            unique_together={('codigo_proveedor', 'proveedor')},
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['fecha'], name='ventas_hist_fecha_a32ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['cliente_id'], name='ventas_hist_cliente_8fac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='ventahistorica',
            index=models.Index(fields=['producto', 'fecha'], name='ventas_hist_product_6a341a_idx'),
        ),
    ]
