# Generated by Django 5.1.4 on 2025-11-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('ofertas_extraidas', models.IntegerField(default=0)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(blank=True, max_length=100)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Archivos Procesados',
                'db_table': 'archivos_procesados',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='fecha_fin',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='laboratorio',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='etllog',
            index=models.Index(fields=['-fecha_ejecucion'], name='idx_etl_fecha'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['activa', 'fecha_fin'], name='idx_activa_fecha_fin'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['laboratorio', 'activa'], name='idx_lab_activa'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['producto', 'activa'], name='idx_prod_activa'),
        ),
        migrations.AddField(
            model_name='archivoprocesado',
            name='etl_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_procesados', to='core.etllog'),
        ),
        migrations.AddIndex(
            model_name='archivoprocesado',
            index=models.Index(fields=['hash_archivo'], name='idx_hash_archivo'),
        ),
        migrations.AddIndex(
            model_name='archivoprocesado',
            index=models.Index(fields=['-fecha_procesamiento'], name='idx_fecha_proc'),
        ),
        migrations.AlterUniqueTogether(
            name='archivoprocesado',
            unique_together={('etl_log', 'hash_archivo')},
        ),
    ]
