# Generated by Django 5.0.4 on 2025-11-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_proveedor_ofertalaboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Venta Histórica',
                'verbose_name_plural': 'Ventas Históricas',
                'db_table': 'ventas_historicas',
                'indexes': [models.Index(fields=['fecha'], name='ventas_hist_fecha_a32ebd_idx'), models.Index(fields=['cliente_id'], name='ventas_hist_cliente_8fac6b_idx'), models.Index(fields=['producto', 'fecha'], name='ventas_hist_product_6a341a_idx')],
            },
        ),
    ]
