# Generated by Django 5.1.4 on 2025-11-05 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venta_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciacompra',
            name='codigo_proveedor',
            field=models.CharField(blank=True, help_text='Código del producto en el catálogo del proveedor', max_length=100),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento si tiene oferta', max_digits=5),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='dias_cobertura',
            field=models.IntegerField(blank=True, help_text='Días de cobertura actuales del producto', null=True),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='incluida_en_orden',
            field=models.BooleanField(default=False, help_text='Si fue incluida en una orden de compra'),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio con oferta si aplica', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario del proveedor recomendado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='proveedor_recomendado',
            field=models.ForeignKey(blank=True, help_text='Proveedor óptimo basado en precio y disponibilidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='sugerenciacompra',
            name='tiene_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sugerenciacompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='core.producto'),
        ),
        migrations.AddIndex(
            model_name='sugerenciacompra',
            index=models.Index(fields=['procesada', 'prioridad'], name='idx_sug_proc_prior'),
        ),
        migrations.AddIndex(
            model_name='sugerenciacompra',
            index=models.Index(fields=['proveedor_recomendado', 'procesada'], name='idx_sug_prov_proc'),
        ),
    ]
