# Generated by Django 5.1.4 on 2025-11-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_archivoprocesado_alter_ofertalaboratorio_activa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(db_index=True, help_text='Código del producto según el proveedor', max_length=100)),
                ('nombre_en_catalogo', models.CharField(blank=True, help_text='Nombre del producto en el catálogo del proveedor', max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Si el mapeo está activo o fue descontinuado')),
                ('confianza', models.DecimalField(decimal_places=2, default=100.0, help_text='Nivel de confianza del mapeo (0-100%). 100% = manual, < 100% = automático', max_digits=5)),
                ('fecha_mapeo', models.DateTimeField(auto_now_add=True)),
                ('mapeado_por', models.CharField(default='manual', help_text="Origen del mapeo: 'manual', 'automatico', 'ml'", max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre el mapeo')),
                ('producto_interno', models.ForeignKey(help_text='Producto del inventario interno', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.producto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que usa este código', on_delete=django.db.models.deletion.CASCADE, related_name='producto_mappings', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Mapeo Producto-Proveedor',
                'verbose_name_plural': 'Mapeos Producto-Proveedor',
                'db_table': 'producto_proveedor_mapping',
                'ordering': ['-fecha_mapeo'],
                'indexes': [models.Index(fields=['codigo_proveedor', 'proveedor'], name='idx_codigo_prov'), models.Index(fields=['producto_interno', 'activo'], name='idx_prod_int_act')],
                'unique_together': {('codigo_proveedor', 'proveedor')},
            },
        ),
    ]
