# Generated by Django 5.1.4 on 2025-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sugerenciacompra_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio sin IVA (precio_unitario / 1.19)', max_digits=12, null=True),
        ),
    ]
