# Generated by Django 5.1.4 on 2025-11-25 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sugerenciacompra_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno (ej: completada, pendiente)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible (ej: Completada, Pendiente)', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_final', models.BooleanField(default=False, help_text='Indica si es un estado final (no puede cambiar)')),
                ('color', models.CharField(blank=True, help_text='Color para UI (ej: green, yellow, red)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Estado de Venta',
                'verbose_name_plural': 'Estados de Venta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno (ej: efectivo, tarjeta)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible (ej: Efectivo, Tarjeta de Crédito)', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_preferente',
            field=models.BooleanField(default=False, help_text='Marcar como proveedor preferente en caso de empate de precios'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='monto_minimo_pedido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de pedido en CLP (0 = sin mínimo)', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_legacy',
            field=models.CharField(blank=True, help_text='Campo legacy - usar estado (FK)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_legacy',
            field=models.CharField(blank=True, help_text='Campo legacy - usar metodo_pago (FK)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.estadoventa'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, help_text='Método de pago utilizado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.metodopago'),
        ),
    ]
