# Generated by Django 5.1.4 on 2025-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productoproveedormapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_inventario_actual',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el producto está en el último Excel de inventario cargado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_carga',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última vez que este producto fue incluido en una carga de Excel', null=True),
        ),
    ]
