# Generated by Django 5.1.4 on 2025-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estadoventa_metodopago_proveedor_es_preferente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_oferta_enviada',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora del último envío de oferta', null=True),
        ),
    ]
