# Generated by Django 5.1.4 on 2025-11-03 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_en_inventario_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para UI', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Catálogo',
                'verbose_name_plural': 'Productos de Catálogo',
                'db_table': 'productos_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto en Inventario', 'verbose_name_plural': 'Productos en Inventario'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='ofertalaboratorio',
            name='idx_prod_activa',
        ),
        migrations.RenameIndex(
            model_name='ofertalaboratorio',
            new_name='idx_oferta_activa_fecha',
            old_name='idx_activa_fecha_fin',
        ),
        migrations.RenameIndex(
            model_name='ofertalaboratorio',
            new_name='idx_oferta_lab_activa',
            old_name='idx_lab_activa',
        ),
        migrations.RemoveField(
            model_name='ofertalaboratorio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='en_inventario_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ultima_carga',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras EAN', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, help_text='Proveedor principal de este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo/compra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta al público', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, help_text='Cantidad física en inventario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10, help_text='Stock mínimo antes de alerta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Nombre de contacto', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='core.categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='idx_prod_codigo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'stock_actual'], name='idx_prod_activo_stock'),
        ),
        migrations.AlterField(
            model_name='ofertalaboratorio',
            name='laboratorio',
            field=models.ForeignKey(blank=True, help_text='Laboratorio fabricante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.laboratorio'),
        ),
        migrations.AddField(
            model_name='productocatalogo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_catalogo', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='productocatalogo',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor que ofrece este producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos_catalogo', to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='ofertalaboratorio',
            name='producto_catalogo',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo de proveedores', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.productocatalogo'),
        ),
        migrations.AddIndex(
            model_name='ofertalaboratorio',
            index=models.Index(fields=['producto_catalogo', 'activa'], name='idx_oferta_prod_activa'),
        ),
        migrations.AddIndex(
            model_name='productocatalogo',
            index=models.Index(fields=['codigo'], name='idx_cat_codigo'),
        ),
        migrations.AddIndex(
            model_name='productocatalogo',
            index=models.Index(fields=['proveedor', 'activo'], name='idx_cat_prov_activo'),
        ),
    ]
