# Generated by Django 5.1.4 on 2025-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_laboratorio_productocatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, help_text='Número de documento de venta', max_length=50, null=True),
        ),
    ]
