# Generated by Django 5.1.4 on 2025-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_neto_to_detalleventa'),
        ('core', '0005_add_ultima_oferta_enviada'),
    ]

    operations = [
    ]
