# Generated by Django 5.1.4 on 2025-11-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_direccion_cliente_rut_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hash_unico',
            field=models.CharField(blank=True, db_index=True, help_text='Hash MD5 único para detectar duplicados: MD5(numero+cliente_rut+fecha)', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['hash_unico'], name='core_venta_hash_un_57d01a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha', 'cliente'], name='core_venta_fecha_0741c8_idx'),
        ),
    ]
